rawdata_C1c1 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD1/CD1col1/output/dge_data/YG-RE-RE1-hpCD1col1_S1_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
print("done")
rawdata_C1c2 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD1/CD1col2/output/dge_data/YG-RE-RE2-hpCD1col2_S1_gene_counts.tsv.gz', header = T, stringsAsFactors = F, row.names = 1) 
print("done")
rawdata_C1c3 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD1/CD1col3/output/dge_data/YG-RE-RE3-hpCD1col3_S1_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
print("done")
rawdata_C1c4 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD1/CD1col4/output/dge_data/YG-RE-RE4-hpCD1col4_S1_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
print("done")
rawdata_C1c5 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD1/CD1col5/output/dge_data/YG-RE-RE5-hpCD1col5_S1_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1)
print("done")
rawdata_C1c6 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD1/CD1col6/output/dge_data/YG-RE-RE6-hpCD1col6_S1_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
print("done")
rawdata_C2c1 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD2/CD2col1/output/dge_data/YG-RE-RE3-hpCD2col1_S2_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C2c2 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD2/CD2col2/output/dge_data/YG-RE-RE4-hpCD2col2_S2_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1)
rawdata_C2c3 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD2/CD2col3/output/dge_data/YG-RE-RE5-hpCD2col3_S2_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C2c4 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD2/CD2col4/output/dge_data/YG-RE-RE6-hpCD2col4_S2_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C2c5 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD2/CD2col5/output/dge_data/YG-RE-RE2-hpCD2col5_S2_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C2c6 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD2/CD2col6/output/dge_data/YG-RE-RE1-hpCD2col6_S2_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C3c1 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD3/CD3col1/output/dge_data/YG-RE-RE4-hpCD3col1_S3_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C3c2 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD3/CD3col2/output/dge_data/YG-RE-RE3-hpCD3col2_S3_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C3c3 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD3/CD3col3/output/dge_data/YG-RE-RE2-CD3col3_Unk1_S4_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C3c4 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD3/CD3col4/output/dge_data/YG-RE-RE1-hpCD3col4_S3_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C3c5 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD3/CD3col5/output/dge_data/YG-RE-RE6-hpCD3col5_S3_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1) 
rawdata_C3c6 <-read.table('/project2/gilad/reem/singlecellCM/round1/fulldata/CD3/CD3col6/output/dge_data/YG-RE-RE5-hpCD3col6_S3_gene_counts.tsv.gz',header = T, stringsAsFactors = F, row.names = 1)

# Save all files 
save.image('rawdata.RData')