library(monocle3)

plots_loc <- "./monocle_plots/"
create_plot_png <- function(plt, filename, w = 800, h = 600, t = NA) {
  print(plt)
  if (!is.na(t)) {
    plt <- plt + t
  }
  dev.copy(plt, paste0(plots_loc, filename, ".png"), width = w, height = h)
  dev.off()
}

### No seurat processing
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_processed.RDS")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F)
create_plot_png(plt, "lowpass_PCA_diffday")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F)
create_plot_png(plt, "lowpass_PCA_individual")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F)
create_plot_png(plt, "lowpass_PCA_collection")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F)
create_plot_png(plt, "lowpass_PCA_colday")

plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F)
create_plot_png(plt, "lowpass_UMAP_diffday")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F)
create_plot_png(plt, "lowpass_UMAP_individual")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F)
create_plot_png(plt, "lowpass_UMAP_collection")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F)
create_plot_png(plt, "lowpass_UMAP_colday")
rm(m)

### Basic norm
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_basic_norm_processed.RDS")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_basic_norm_PCA_diffday")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_basic_norm_PCA_individual")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_basic_norm_PCA_collection")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_basic_norm_PCA_colday")

plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_basic_norm_UMAP_diffday")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_basic_norm_UMAP_individual")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_basic_norm_UMAP_collection")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_basic_norm_UMAP_colday")
rm(m)

### No scaling normalization
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_noscale_norm_processed.RDS")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_noscale_norm_PCA_diffday")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_noscale_norm_PCA_individual")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_noscale_norm_PCA_collection")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_noscale_norm_PCA_colday")

plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_noscale_norm_UMAP_diffday")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_noscale_norm_UMAP_individual")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_noscale_norm_UMAP_collection")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_noscale_norm_UMAP_colday")
rm(m)

### SCTransform normalization
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_sctransform_processed.RDS")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_PCA_diffday")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_PCA_individual")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_PCA_collection")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_PCA_colday")

plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_UMAP_diffday")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_UMAP_individual")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_UMAP_collection")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_UMAP_colday")
rm(m)

### SCTransform normalization, mito regression
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_sctransform_mitoregress_processed.RDS")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitoregress_PCA_diffday")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitoregress_PCA_individual")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitoregress_PCA_collection")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitoregress_PCA_colday")

plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitoregress_UMAP_diffday")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitoregress_UMAP_individual")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitoregress_UMAP_collection")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitoregress_UMAP_colday")
rm(m)

### SCTransform normalization, mito and colday regression
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_sctransform_mitocoldayregress_processed.RDS")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitocoldayregress_PCA_diffday")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitocoldayregress_PCA_individual")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitocoldayregress_PCA_collection")
plt <- plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitocoldayregress_PCA_colday")

plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitocoldayregress_UMAP_diffday")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitocoldayregress_UMAP_individual")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitocoldayregress_UMAP_collection")
plt <- plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
create_plot_png(plt, "lowpass_sctransform_mitocoldayregress_UMAP_colday")
rm(m)
