library(monocle3)

plots_loc <- "./monocle_plots/"
### No seurat processing
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_processed.RDS")
png(paste0(plots_loc, "lowpass_PCA_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F)
dev.off()
png(paste0(plots_loc, "lowpass_PCA_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F)
dev.off()
png(paste0(plots_loc, "lowpass_PCA_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F)
dev.off()
png(paste0(plots_loc, "lowpass_PCA_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F)
dev.off()

png(paste0(plots_loc, "lowpass_UMAP_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F)
dev.off()
png(paste0(plots_loc, "lowpass_UMAP_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F)
dev.off()
png(paste0(plots_loc, "lowpass_UMAP_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F)
dev.off()
png(paste0(plots_loc, "lowpass_UMAP_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F)
dev.off()
rm(m)

### Basic norm
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_basic_norm_processed.RDS")
png(paste0(plots_loc, "lowpass_basic_norm_PCA_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_basic_norm_PCA_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_basic_norm_PCA_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_basic_norm_PCA_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()

png(paste0(plots_loc, "lowpass_basic_norm_UMAP_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_basic_norm_UMAP_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_basic_norm_UMAP_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_basic_norm_UMAP_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()
rm(m)

### No scaling normalization
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_noscale_norm_processed.RDS")
png(paste0(plots_loc, "lowpass_noscale_norm_PCA_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_noscale_norm_PCA_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_noscale_norm_PCA_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_noscale_norm_PCA_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()

png(paste0(plots_loc, "lowpass_noscale_norm_UMAP_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_noscale_norm_UMAP_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_noscale_norm_UMAP_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_noscale_norm_UMAP_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()
rm(m)


### SCTransform normalization
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_sctransform_processed.RDS")
png(paste0(plots_loc, "lowpass_sctransform_PCA_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_PCA_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_PCA_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_PCA_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()

png(paste0(plots_loc, "lowpass_sctransform_UMAP_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_UMAP_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_UMAP_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_UMAP_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()
rm(m)


### SCTransform normalization, mito regression
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_sctransform_mitoregress_processed.RDS")
png(paste0(plots_loc, "lowpass_sctransform_mitoregress_PCA_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitoregress_PCA_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitoregress_PCA_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitoregress_PCA_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()

png(paste0(plots_loc, "lowpass_sctransform_mitoregress_UMAP_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitoregress_UMAP_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitoregress_UMAP_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitoregress_UMAP_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()
rm(m)

### SCTransform normalization, mito and colday regression
m <- readRDS("./rds_objects/monocle_from_seurat_lowpass_sctransform_mitocoldayregress_processed.RDS")
png(paste0(plots_loc, "lowpass_sctransform_mitocoldayregress_PCA_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitocoldayregress_PCA_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitocoldayregress_PCA_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitocoldayregress_PCA_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="PCA", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()

png(paste0(plots_loc, "lowpass_sctransform_mitocoldayregress_UMAP_diffday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="diffday", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitocoldayregress_UMAP_individual.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="individual", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitocoldayregress_UMAP_collection.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="collection", label_cell_groups=F, norm_method="size_only")
dev.off()
png(paste0(plots_loc, "lowpass_sctransform_mitocoldayregress_UMAP_colday.png"), width=800, height=600)
plot_cells(m, reduction_method="UMAP", color_cells_by="colday", label_cell_groups=F, norm_method="size_only")
dev.off()
rm(m)
